struct Matrix4x4
        m11     dd      ?
        m12     dd      ?
        m13     dd      ?
        m14     dd      ?
        m21     dd      ?
        m22     dd      ?
        m23     dd      ?
        m24     dd      ?
        m31     dd      ?
        m32     dd      ?
        m33     dd      ?
        m34     dd      ?
        m41     dd      ?
        m42     dd      ?
        m43     dd      ?
        m44     dd      ?
ends

struct Vector3
        x               dd ?
        y               dd ?
        z               dd ?
ends