;See Units\Blocks\BlocksIndexes.const to verify dependencies
       
TextureNames:                          
        db      "Log_16.mbmw", 0          
        db      "Planks_16.mbmw", 0   
        db      "Chest_16.mbmw", 0  
        db      "CraftBlock_16.mbmw", 0
        db      "Turf_16.mbmw", 0    
        db      "Dirt_16.mbmw", 0 
        db      "DiamondOre_16.mbmw", 0 ;none  
        db      "Sand_16.mbmw", 0   
        db      "Sand_16.mbmw", 0 
        db      "lamp_16.mbmw", 0  
        db      "Gravel_16.mbmw", 0 
        db      "Cobblestone_16.mbmw", 0   
        db      "Stone_16.mbmw", 0 
        db      "Furance_16.mbmw", 0   
        db      "Wool_16.mbmw", 0 
        db      "DiamondOre_16.mbmw", 0 ;none  
        db      "Bedrock_16.mbmw", 0  
        db      "IroneOre_16.mbmw", 0   
        db      "GoldOre_16.mbmw", 0  
        db      "CoalOre_16.mbmw", 0    
        db      "DiamondOre_16.mbmw", 0   
        db      "Leaves_16.mbmw", 0 
        db      0
        
TextureHandles:
              gf_block.Log            dd ?    ; = 1
              gf_block.Planks         dd ?    ; = 2
              gf_block.Chest          dd ?    ; = 3
              gf_block.CraftingTable  dd ?    ; = 4
              gf_block.Dirt           dd ?    ; = 5
              gf_block.Turf           dd ?    ; = 6
              gf_block.Tallgrass      dd ?    ; = 7
              gf_block.Sand           dd ?    ; = 8
              gf_block.Sandstone      dd ?    ; = 9
              gf_block.Glass          dd ?    ; = 10
              gf_block.Gravel         dd ?    ; = 11
              gf_block.Cobblestone    dd ?    ; = 12
              gf_block.Stone          dd ?    ; = 13
              gf_block.Furnace        dd ?    ; = 14
              gf_block.Wool           dd ?    ; = 15
              gf_block.Bed            dd ?    ; = 16
              gf_block.Bedrock        dd ?    ; = 17
              gf_block.IronOre        dd ?    ; = 18
              gf_block.GoldOre        dd ?    ; = 19
              gf_block.CoalOre        dd ?    ; = 20
              gf_block.DiamondOre     dd ?    ; = 21
 WithDiskard: gf_block.Leaves         dd ?    ; = 22
              tx_EOF:




