ObjectsNames:     
        obj.Label.Name            db      "Blini.mobj", 0
        obj.Player.Hand.Name      db      "Player\RHandpl.mobj", 0
        obj.Cube.Name             db      "LCube.mobj", 0                     
        obj.Player.Body.Name      db      "Player\Body.mobj", 0
        obj.Player.LLeg.Name      db      "Player\LLeg.mobj", 0
        obj.Player.RLeg.Name      db      "Player\RLeg.mobj", 0
        obj.Player.LHand.Name     db      "Player\LHand.mobj", 0
        obj.Player.RHand.Name     db      "Player\RHand.mobj", 0
        obj.Pickaxe.Name          db      "Pickaxe.mobj", 0
        db      0
        
ObjectsHandles:
        obj.Label.Handle           dd     ?, ?
        obj.Player.Hand.Handle     dd     ?, ?
        obj.Cube.Handle            dd     ?, ?
        obj.Player.Body.Handle     dd     ?, ?
        obj.Player.LLeg.Handle     dd     ?, ?
        obj.Player.RLeg.Handle     dd     ?, ?
        obj.Player.LHand.Handle    dd     ?, ?
        obj.Player.RHand.Handle    dd     ?, ?
        obj.Pickaxe.Handle         dd     ?, ?
        obj_EOF:





