TextureNames:                          
        db      "Log_19.mbmw", 0
        db      "Brick_64.mbmw", 0   
        db      "Brick_64.mbmw", 0 
        db      "Brick_64.mbmw", 0   
        db      "Brick_64.mbmw", 0 
        db      "Brick_64.mbmw", 0   
        db      "Brick_64.mbmw", 0 
        db      "Brick_64.mbmw", 0   
        db      "Brick_64.mbmw", 0 
        db      "Brick_64.mbmw", 0   
        db      "Brick_64.mbmw", 0 
        db      "Brick_64.mbmw", 0   
        db      "Log_19.mbmw", 0 
        db      "Brick_64.mbmw", 0   
        db      "Brick_64.mbmw", 0 
        db      "Brick_64.mbmw", 0   
        db      "Brick_64.mbmw", 0 
        db      "Brick_64.mbmw", 0   
        db      "Brick_64.mbmw", 0 
        db      "Brick_64.mbmw", 0   
        db      "Brick_64.mbmw", 0 
        db      "Brick_64.mbmw", 0 
        db      0
        
TextureHandles:
              gf_block.Log            dd ?
              gf_block.Planks         dd ?
              gf_block.Chest          dd ?
              gf_block.CraftingTable  dd ?
              gf_block.Dirt           dd ?
              gf_block.Turf           dd ?
              gf_block.Tallgrass      dd ?
              gf_block.Sand           dd ?
              gf_block.Sandstone      dd ?
              gf_block.Glass          dd ?
              gf_block.Gravel         dd ?
              gf_block.Cobblestone    dd ?
              gf_block.Stone          dd ?  
              gf_block.Furnace        dd ?
              gf_block.Wool           dd ?
              gf_block.Bed            dd ?
              gf_block.Bedrock        dd ?
              gf_block.IronOre        dd ?
              gf_block.GoldOre        dd ?
              gf_block.CoalOre        dd ?
              gf_block.DiamondOre     dd ?
 WithDiskard: gf_block.Leaves         dd ?
              tx_EOF:








