AddictionalTextureNames:                          
              db      "Player_1.mbmw", 0
              ;Attention!!! Add your textures names in this field
              ;=====================================
              ;Your textures names:
              ;db     "texture.mbmw", 0
              ;...
              ;=====================================
              db      "Pickaxe\Wood_32.mbmw", 0
              db      "Pickaxe\Stone_32.mbmw", 0
              db      "Pickaxe\Iron_32.mbmw", 0
              db      "Pickaxe\Gold_32.mbmw", 0
              db      "Pickaxe\Diamond_32.mbmw", 0
              db      0
        
AddictionalTextureHandles:    
              tx.Player.Handle   dd   ?
              ;Attention!!! Add your objs in this field
              ;=====================================
              ;Your textures:
              ;tx.YouTexture.Handle       dd     ?
              ;...
              ;=====================================
ToolsTxAddr:  tx.Pickaxe.Wood.Handle      dd     ?
              tx.Pickaxe.Stone.Handle     dd     ? 
              tx.Pickaxe.Iron.Handle      dd     ? 
              tx.Pickaxe.Gold.Handle      dd     ? 
              tx.Pickaxe.Diamond.Handle   dd     ?  
              tx.Axe.Wood.Handle          dd     ?
              tx.Axe.Stone.Handle         dd     ? 
              tx.Axe.Iron.Handle          dd     ? 
              tx.Axe.Gold.Handle          dd     ? 
              tx.Axe.Diamond.Handle       dd     ?  
              tx.Showel.Wood.Handle       dd     ?
              tx.Showel.Stone.Handle      dd     ? 
              tx.Showel.Iron.Handle       dd     ? 
              tx.Showel.Gold.Handle       dd     ? 
              tx.Showel.Diamond.Handle    dd     ? 
              tx.Sword.Wood.Handle        dd     ?
              tx.Sword.Stone.Handle       dd     ? 
              tx.Sword.Iron.Handle        dd     ? 
              tx.Sword.Gold.Handle        dd     ? 
              tx.Sword.Diamond.Handle     dd     ? 








