include "units\interfase_items.INC"
include "units\interfase_text.INC"

CuruiTurn   dd  ?

backGroundAdd  dd  0.0


PLAY_text      db   'Play'
CONNECT_text   db   'Connect'
EXIT_text      db   'Exit'

BACK_text      db   'Back'
Menu_text      db   'Menu'
Continue_text  db   'Continue'
Create_text    db   'Create'
Open_text      db   'Open'

TEXT_text      db   'text'

version_text      db   'blincraft v1.0'
version_text_len  dd   $ - version_text

num_text         db    ?, ?, ?, ?





